import dataclasses
import httpx
from nexosapi.config.settings.services import NexosAIAPIConfiguration as NexosAIAPIConfiguration
from typing import Any

@dataclasses.dataclass
class NexosAPIService:
    base_url: str = ...
    def __post_init__(self) -> None: ...
    def initialize(self, config: NexosAIAPIConfiguration) -> None: ...
    def construct_headers(self, config: NexosAIAPIConfiguration) -> dict[str, str]: ...
    def construct_auth(self, config: NexosAIAPIConfiguration) -> httpx.Auth | None: ...
    async def request(self, verb: str, url: str, override_base: bool = False, **kwargs: Any) -> httpx.Response: ...
    async def disconnect(self) -> None: ...
