name: Build Docs

on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-docs
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Build documentation
        run: poetry run mkdocs build
      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
