name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --all-extras
      - name: Run Ruff (Python linter)
        run: poetry run ruff check --config pyproject.toml
      - name: Run Mypy (type checker)
        run: poetry run mypy . --config-file pyproject.toml
