name: Build and Publish

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-pub
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION_REF: ${{ github.event.ref }}
    steps:
    - name: Get release version from ref
      id: get_release_version
      run: echo "RELEASE_VERSION=$(echo $RELEASE_VERSION_REF | cut -d '/' -f 3)" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install --all-extras
    - name: Build package
      run: poetry build
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        verify-metadata: false
